### ISSUE TITLE
Enchance errors

### ISSUE THREAD

**Issue by floatdrop** [floatdrop/deps-graph#2]
```
`Error: Not found `vendors/islands-page/common.blocks/i-global` in any levels.`
```

For now errors is helping, but they could be better. They should tell about `from where` this block was required and how it was searched through graph.

**Comment by iamstarkov** [comment]
Error can be like this:

```
Error: Not found `i-global` in any levels _required_ by `{bem.id}` in `{level}` level`.
```

**Comment by iamstarkov** [comment]
How to show search path graph is more complicated issue

**Comment by iamstarkov** [comment]
> Error: Not found `i-global` in any levels _required_ by `{bem.id}` in `{level}` level`.

For implementing this error format method `deps` should have access to block, which is need current block (for which we build deps now) and need type (require or expect)

**Comment by floatdrop** [comment]
Done.
