### ISSUE TITLE
deliver "module.exports" format of deps

### ISSUE THREAD

**Issue by iamstarkov** [floatdrop/deps-graph#4]
We should use require-or-die to let users use both format of deps file: BEM-format and Modules-format.

**Comment by floatdrop** [comment]
I thought I added it.

P.s. I'm planning to add json support to require-or-die and omit extension of deps file. This will allow to use Jsons as deps files to. Is this okay?

**Comment by iamstarkov** [comment]
This is ok:
// module format *.deps.js

``` js
module.exports { require: [], expect: [] }
```

This is seems to be ok:
// legacy format *.deps.js

``` js
({ require: [], expect: [] })
```

You want to add new deps standart?
// json format *.deps.json

``` js
{ require: [], expect: [] }
```
